/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Ventana;

/**
 *
 * @author chelvivil
 */
public class GUI_Informacion extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InformacionEstudinte
     */
    public GUI_Informacion() {
        initComponents();
    }
    public String [] devolverInformacion(){
        String arreglo[]= new String [4];
        arreglo[0]=this.jt_NumeroDelRegistro.getText();
        arreglo[1]=this.jt_NombreDelDueño.getText();
          arreglo[2]=this.jt_Cedula.getText();
        arreglo[3]=this.jt_Placa.getText();
        
        return arreglo;
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.jt_NombreDelDueño.setText(arreglo[0]);
        this.jt_Cedula.setText(arreglo[1]);
                this.jt_Placa.setText(arreglo[2]);

        
    }
    public void habilitarAgregar()
    {
        this.jt_NombreDelDueño.setEnabled(true);

        this.jt_NumeroDelRegistro.setEnabled(true);
        this.jt_Cedula.setEnabled(true);
                this.jt_Placa.setEnabled(true);

             

    }
public void estadoInicial(){
this.jt_NumeroDelRegistro.setEnabled(true);
this.jt_NombreDelDueño.setEnabled(false);
this.jt_Cedula.setEnabled(false);
this.jt_Placa.setEnabled(false);

}

public void limpiar(){
this.jt_Cedula.setText("");
this.jt_NombreDelDueño.setText("");
this.jt_Cedula.setText("");
this.jt_Placa.setText("");
}
public void deshabilitarNumeroDeRegistro(){
   this.jt_NumeroDelRegistro.setEnabled(false);
this.jt_NombreDelDueño.setEnabled(true);
this.jt_Cedula.setEnabled(true);
this.jt_Placa.setEnabled(true);
 
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Cedula = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Direccion = new javax.swing.JLabel();
        jt_NumeroDelRegistro = new javax.swing.JTextField();
        jt_NombreDelDueño = new javax.swing.JTextField();
        jt_Placa = new javax.swing.JTextField();
        jl_Direccion1 = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();

        jl_Cedula.setText("Numero de registro");

        jl_Nombre.setText("Nombre");

        jl_Direccion.setText("Cedula");

        jl_Direccion1.setText("Placa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_Cedula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Nombre, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_NombreDelDueño)
                            .addComponent(jt_NumeroDelRegistro))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_Direccion)
                        .addGap(44, 44, 44)
                        .addComponent(jt_Cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jl_Direccion1)
                        .addGap(35, 35, 35)
                        .addComponent(jt_Placa, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Cedula)
                    .addComponent(jt_NumeroDelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(jt_NombreDelDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Direccion)
                    .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Direccion1)
                    .addComponent(jt_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Direccion;
    private javax.swing.JLabel jl_Direccion1;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_NombreDelDueño;
    private javax.swing.JTextField jt_NumeroDelRegistro;
    private javax.swing.JTextField jt_Placa;
    // End of variables declaration//GEN-END:variables
}
